export const PERMISSIONS = Object.freeze({
  USER_READ: 'user:read',
  USER_WRITE: 'user:write',
  USER_DELETE: 'user:delete',
  ROLE_READ: 'role:read',
  ROLE_WRITE: 'role:write',
  INVITATION_READ: 'invitation:read',
  INVITATION_WRITE: 'invitation:write',
  COURSE_READ: 'course:read',
  COURSE_WRITE: 'course:write',
  COURSE_PUBLISH: 'course:publish',
  COURSE_DELETE: 'course:delete',
  ENROLLMENT_READ: 'enrollment:read',
  ENROLLMENT_WRITE: 'enrollment:write',
  ASSESSMENT_READ: 'assessment:read',
  ASSESSMENT_WRITE: 'assessment:write',
  ASSESSMENT_GRADE: 'assessment:grade',
  CERTIFICATE_READ: 'certificate:read',
  CERTIFICATE_ISSUE: 'certificate:issue',
  ANALYTICS_READ: 'analytics:read',
  SUBSCRIPTION_READ: 'subscription:read',
  SUBSCRIPTION_MANAGE: 'subscription:manage',
  TENANT_READ: 'tenant:read',
  TENANT_MANAGE: 'tenant:manage',
});
