/** Path fragments appended to environment.apiBaseUrl by the axios instance. */
export const API_ENDPOINTS = Object.freeze({
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    logoutAll: '/auth/logout-all',
    refresh: '/auth/refresh',
    me: '/auth/me',
    sessions: '/auth/sessions',
    revokeSession: (sessionId) => `/auth/sessions/${sessionId}`,
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    acceptInvitation: '/auth/accept-invitation',
  },
  users: {
    base: '/users',
    byId: (id) => `/users/${id}`,
    activate: (id) => `/users/${id}/activate`,
    deactivate: (id) => `/users/${id}/deactivate`,
    lock: (id) => `/users/${id}/lock`,
    unlock: (id) => `/users/${id}/unlock`,
    statusHistory: (id) => `/users/${id}/status-history`,
    roles: (id) => `/users/${id}/roles`,
    changePassword: '/users/me/password',
  },
  roles: {
    base: '/roles',
    byId: (id) => `/roles/${id}`,
  },
  permissions: {
    base: '/permissions',
    byId: (id) => `/permissions/${id}`,
  },
  invitations: {
    base: '/invitations',
    byId: (id) => `/invitations/${id}`,
    resend: (id) => `/invitations/${id}/resend`,
  },
  courses: {
    base: '/courses',
    byId: (id) => `/courses/${id}`,
    publish: (id) => `/courses/${id}/publish`,
    unpublish: (id) => `/courses/${id}/unpublish`,
    archive: (id) => `/courses/${id}/archive`,
    submit: (id) => `/courses/${id}/submit`,
    approve: (id) => `/courses/${id}/approve`,
    reject: (id) => `/courses/${id}/reject`,
    recordings: (id) => `/courses/${id}/recordings`,
    thumbnail: (id) => `/courses/${id}/thumbnail`,
    mine: '/courses/mine',
  },
  adminEnrollments: {
    base: '/admin/enrollments',
    byId: (id) => `/admin/enrollments/${id}`,
    status: (id) => `/admin/enrollments/${id}/status`,
  },
  instructorEnrollments: {
    base: '/instructor/enrollments',
    byId: (id) => `/instructor/enrollments/${id}`,
    status: (id) => `/instructor/enrollments/${id}/status`,
  },
  studentEnrollments: {
    base: '/student/enrollments',
    byId: (id) => `/student/enrollments/${id}`,
  },
  learning: {
    course: (courseId) => `/learning/courses/${courseId}`,
    lesson: (courseId, lessonId) => `/learning/courses/${courseId}/lessons/${lessonId}`,
    progress: (courseId) => `/learning/courses/${courseId}/progress`,
  },
  assessments: {
    base: '/assessments',
    byId: (id) => `/assessments/${id}`,
    attempts: (id) => `/assessments/${id}/attempts`,
    submit: (attemptId) => `/assessments/attempts/${attemptId}/submit`,
    result: (attemptId) => `/assessments/attempts/${attemptId}/result`,
  },
  adminAssessments: {
    base: '/admin/assessments',
    byId: (id) => `/admin/assessments/${id}`,
    publish: (id) => `/admin/assessments/${id}/publish`,
    unpublish: (id) => `/admin/assessments/${id}/unpublish`,
    close: (id) => `/admin/assessments/${id}/close`,
    archive: (id) => `/admin/assessments/${id}/archive`,
    questions: (assessmentId) => `/admin/assessments/${assessmentId}/questions`,
    questionById: (assessmentId, questionId) =>
      `/admin/assessments/${assessmentId}/questions/${questionId}`,
    updateQuestion: (questionId) => `/admin/assessments/questions/${questionId}`,
    analytics: (id) => `/admin/assessments/${id}/analytics`,
  },
  certificates: {
    base: '/certificates',
    byId: (id) => `/certificates/${id}`,
    download: (id) => `/certificates/${id}/download`,
  },
  notifications: {
    base: '/notifications',
    read: (id) => `/notifications/${id}/read`,
    readAll: '/notifications/read-all',
  },
  analytics: {
    admin: '/analytics/admin',
    instructor: '/analytics/instructor',
    studentProgress: '/analytics/progress',
  },
  subscriptions: {
    current: '/subscriptions/current',
    plans: '/subscriptions/plans',
    billingHistory: '/subscriptions/billing',
  },
  tenants: {
    current: '/tenants/current',
    settings: '/tenants/current/settings',
    branding: '/tenants/current/branding',
  },
  profile: {
    base: '/profile',
    avatar: '/profile/avatar',
    changePassword: '/profile/change-password',
  },
});
